### PR TITLE
add implicit https support and sample files

### PR DESCRIPTION
**Pull request by stewartoallen**
add implicit https support when a valid tls certificate and key are supplied
add sample cert and key files that can simply be renamed for local testing

### CODE REVIEW

**Comment by stewartoallen** [comment]
TLS/HTTPS support is required when either chilipeppr.com is framed in a secure site or an SPJS server needs to be reached from a secure site.  My workaround has been to run stunnel in front of SPJS (fine on mac/linux), but this is a huge challenge for Windows users.  Integrating native https support alleviates this problem and allows for SPJS to be the only app required.

**Comment by chilipeppr** [comment]
This is a spectacular pull request. Wow! I can't wait to test it out. We
all thank you graciously.

**Comment by openhardwarecoza** [comment]
Yay now i'll feel less queezy about the shell access too (;

**Comment by stewartoallen** [comment]
I was going to get fancy and have it generate it's own self-signed certs.  lmk if you think that's a good cmd-line option for the future.

**Comment by openhardwarecoza** [comment]
Integrate some letsencrypt.org (;

**Comment by stewartoallen** [comment]
sure!  at least that's a great link to add in the docs.  cert/key gen has always been problematic for end users.

**Comment by raykholo** [comment]
I must be dreaming.  Phenomenal.

**Comment by mikejac** [comment]
Security is a bitch! :-)

1) If possible, the HTTPS-server should be forced to accept only TLS v. 1.2 and up. Previous versions are not considered safe anymore.

2) The certificate on SPJS. The sample-cert provided will only work if CP connects to 'localhost'. If you connect by ip-address it will not work. 

Haven't tried, but my guess is that Chrome will tell you that the sample-cert is "dangerous" (self-signed)? 

IMHO, only "real" certs are good enough - we don't want to get used to simply accepting "dangerous" certificates.

So I'll second Peter's idea of integrating letsencrypt.org certs into SPJS. Certficates from letsencrypt.org only have lifespan of 3 months. Onto studying how their scripts work and recreate that functionality into SPJS...

/michael

**Comment by mikejac** [comment]
This seems to be a place to start (letsencrypt + ACME Protocol + go):

https://github.com/riobard/go-acme

/michael

**Comment by openhardwarecoza** [comment]
The fact that they are auto scriptable makes it a big win...  Let spjs do
the lifting for the user

**Comment by stewartoallen** [comment]
I suspect that a lot of these installations are on local networks.  Real certificates may not apply.  I know that that applies to my use case and that of my local maker space.  As long as the security details are documented, I firmly believe these choices should be in the hands of the users.  For me, the driver is being able to reach SPJS from within a secure frame inside Onshape in order to drive a network attached mill.  My workaround has been to put stunnel in front of SPJS.  This is one less shim in the connectivity layer.  I guess my appeal is to not let the perfect get in the way of the good: add the scriptable bits and other integration later.  It works now if you have a cert/key, and that's good enough to be helpful to a lot of folks.

**Comment by chilipeppr** [comment]
My goal too is simply to have HTTPS so I can load a secure websocket so we
can do WebRTC and other items that require SSL. Not having a wss://
websocket connection has been a problem. Since 99% of folks run SPJS on a
local network I don't think we need real certificates, however it is
annoying to have to tell the browser to trust the certificate each time.
So, real certs would be nice.

**Pull request merged**
